import React from "react";

class Data extends React.Component {
  ordersStats = [
    {
      id: 723,
      _package: {
        id: 721,
        sender: {
          first_name: "Nand",
          last_name: "Kadivar",
          phone: null,
          email: "kadivarnand007@gmail.com",
          password:
            "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: "44.6353692",
          longitude: "-63.5894446",
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 4, 0, 5, 1],
          updated_at: [2023, 4, 1, 18, 49, 4],
          username: null,
          user_id: 40,
          authorities: null,
          enabled: true,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
        },
        title: "Package request by Nand Kadivar",
        description: "test courier",
        width: 1.0,
        length: 1.0,
        heigth: 0.0,
        pickup_address: "Chandigarh",
        drop_address: "Ludhiana",
        created_at: [2023, 4, 1, 18, 50, 12],
        updated_at: [2023, 4, 1, 18, 50, 12],
      },
      sender: {
        first_name: "Nand",
        last_name: "Kadivar",
        phone: null,
        email: "kadivarnand007@gmail.com",
        password:
          "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
        gov_id_url: null,
        profile_pic_url: null,
        dob: null,
        address: null,
        city: null,
        latitude: "44.6353692",
        longitude: "-63.5894446",
        province: null,
        postal_code: null,
        country: null,
        is_activated: null,
        is_verified: true,
        created_at: [2023, 3, 4, 0, 5, 1],
        updated_at: [2023, 4, 1, 18, 49, 4],
        username: null,
        user_id: 40,
        authorities: null,
        enabled: true,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
      },
      deliverer: {
        first_name: "shahraj",
        last_name: "singh",
        phone: null,
        email: "singhshahraj@gmail.com",
        password:
          "$2a$10$aw/IY8Ff/Vwb0uspc4oHLO7NBtJAKZalOBnL.usOI/S2FwuTtJjne",
        gov_id_url: null,
        profile_pic_url: null,
        dob: null,
        address: null,
        city: null,
        latitude: "44.6353869",
        longitude: "-63.5894629",
        province: null,
        postal_code: null,
        country: null,
        is_activated: null,
        is_verified: true,
        created_at: [2023, 3, 21, 20, 3, 19],
        updated_at: [2023, 4, 1, 18, 51, 13],
        username: null,
        user_id: 372,
        authorities: null,
        enabled: true,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
      },
      driverRoute: {
        driverId: "372",
        driverName: "shahraj singh",
        sourceCity: "Chandigarh",
        sourceCityReferenceId: "ChIJa8lu5gvtDzkR_hlzUvln_6U",
        destinationCity: "Ludhiana",
        destinationCityReferenceId: "ChIJfVo0YnSDGjkREAbGjjQCEWg",
        maxPackages: 1,
        maxLength: 1,
        maxWidth: 1,
        maxHeight: 1,
        pickupDate: 1680393600000,
        dropoffDate: 1680393600000,
        daysToDeliver: 1,
        pickupLocationCoords: [30.7333148, 76.7794179],
        dropoffLocationCoords: [30.900965, 75.8572758],
        allowedCategory: ["Documents", "Fragile"],
        radius: 0,
        price: 100,
        driverRouteId: 30,
      },
      pickup_code: 5550,
      drop_code: 5326,
      paymentStatus: 0,
      created_at: [2023, 4, 1, 18, 50, 54],
      updated_at: [2023, 4, 1, 18, 50, 54],
      delivered: false,
      canceled: false,
      started: false,
    },
  ];
  requests = [
    {
      sender: {
        first_name: "Rahul",
        last_name: "Saliya",
        phone: null,
        email: "rhs.dev@yopmail.com",
        password:
          "$2a$10$IO9g1OaXo7iGihVk2RuUr.RFiHA5Z204Uk08Z9Adkk2AI9hcQ26B6",
        gov_id_url: null,
        profile_pic_url: null,
        dob: null,
        address: null,
        city: null,
        latitude: null,
        longitude: null,
        province: null,
        postal_code: null,
        country: null,
        is_activated: null,
        is_verified: true,
        created_at: [2023, 3, 15, 23, 37, 55],
        updated_at: [2023, 3, 15, 23, 38, 11],
        username: null,
        authorities: null,
        user_id: 220,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
        enabled: true,
      },
      deliverer: {
        first_name: "Nand",
        last_name: "Kadivar",
        phone: null,
        email: "kadivarnand007@gmail.com",
        password:
          "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
        gov_id_url: null,
        profile_pic_url: null,
        dob: null,
        address: null,
        city: null,
        latitude: "44.6476° N",
        longitude: "63.5728° W",
        province: null,
        postal_code: null,
        country: null,
        is_activated: null,
        is_verified: true,
        created_at: [2023, 3, 4, 0, 5, 1],
        updated_at: [2023, 3, 22, 23, 48, 43],
        username: null,
        authorities: null,
        user_id: 40,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
        enabled: true,
      },
      _package: {
        id: 593,
        sender: {
          first_name: "Rahul",
          last_name: "Saliya",
          phone: null,
          email: "rhs.dev@yopmail.com",
          password:
            "$2a$10$IO9g1OaXo7iGihVk2RuUr.RFiHA5Z204Uk08Z9Adkk2AI9hcQ26B6",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: null,
          longitude: null,
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 15, 23, 37, 55],
          updated_at: [2023, 3, 15, 23, 38, 11],
          username: null,
          authorities: null,
          user_id: 220,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          enabled: true,
        },
        title: "ABC",
        description: "detailed description of the package",
        width: 30.0,
        length: 40.0,
        heigth: 0.0,
        pickup_address: "Point A",
        drop_address: "Point B",
        created_at: [2023, 3, 30, 0, 11, 35],
        updated_at: [2023, 3, 30, 0, 11, 35],
      },
      driverRoute: {
        driverId: "40",
        driverName: "Nand Kadivar",
        sourceCity: "Delhi",
        sourceCityReferenceId: "ChIJLbZ-NFv9DDkRQJY4FbcFcgM",
        destinationCity: "Gujarat",
        destinationCityReferenceId: "ChIJlfcOXx8FWTkRLlJU7YfYG4Y",
        maxPackages: 2,
        maxLength: 1,
        maxWidth: 1,
        maxHeight: 1,
        pickupDate: 1680134400000,
        dropoffDate: 1680134400000,
        daysToDeliver: 1,
        pickupLocationCoords: [28.7040592, 77.10249019999999],
        dropoffLocationCoords: [22.6708317, 71.5723953],
        allowedCategory: ["Documents", "Fragile"],
        radius: 0,
        price: 100,
        driverRouteId: 25,
      },
      aksPrice: 200.0,
      created_at: [2023, 3, 30, 0, 15, 44],
      updated_at: [2023, 3, 30, 0, 17, 45],
      status: "accepted",
      package_request_id: 595,
    },
    {
      sender: {
        first_name: "shahraj",
        last_name: "singh",
        phone: null,
        email: "singhshahraj@gmail.com",
        password:
          "$2a$10$4oDo0UE4Ji.7dLMEIQD2KuUdNkrsmXmtoLEidWLCR25oYiZIR9SFC",
        gov_id_url: null,
        profile_pic_url: null,
        dob: null,
        address: null,
        city: null,
        latitude: null,
        longitude: null,
        province: null,
        postal_code: null,
        country: null,
        is_activated: null,
        is_verified: true,
        created_at: [2023, 3, 21, 20, 3, 19],
        updated_at: [2023, 3, 21, 20, 3, 50],
        username: null,
        authorities: null,
        user_id: 372,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
        enabled: true,
      },
      deliverer: {
        first_name: "Nand",
        last_name: "Kadivar",
        phone: null,
        email: "kadivarnand007@gmail.com",
        password:
          "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
        gov_id_url: null,
        profile_pic_url: null,
        dob: null,
        address: null,
        city: null,
        latitude: "44.6476° N",
        longitude: "63.5728° W",
        province: null,
        postal_code: null,
        country: null,
        is_activated: null,
        is_verified: true,
        created_at: [2023, 3, 4, 0, 5, 1],
        updated_at: [2023, 3, 22, 23, 48, 43],
        username: null,
        authorities: null,
        user_id: 40,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
        enabled: true,
      },
      _package: {
        id: 605,
        sender: {
          first_name: "shahraj",
          last_name: "singh",
          phone: null,
          email: "singhshahraj@gmail.com",
          password:
            "$2a$10$4oDo0UE4Ji.7dLMEIQD2KuUdNkrsmXmtoLEidWLCR25oYiZIR9SFC",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: null,
          longitude: null,
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 21, 20, 3, 19],
          updated_at: [2023, 3, 21, 20, 3, 50],
          username: null,
          authorities: null,
          user_id: 372,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          enabled: true,
        },
        title: "Package request by shahraj singh",
        description: "test",
        width: 1.0,
        length: 1.0,
        heigth: 0.0,
        pickup_address: "Delhi",
        drop_address: "Gujarat",
        created_at: [2023, 3, 30, 1, 22, 20],
        updated_at: [2023, 3, 30, 1, 22, 20],
      },
      driverRoute: {
        driverId: "40",
        driverName: "Nand Kadivar",
        sourceCity: "Delhi",
        sourceCityReferenceId: "ChIJLbZ-NFv9DDkRQJY4FbcFcgM",
        destinationCity: "Gujarat",
        destinationCityReferenceId: "ChIJlfcOXx8FWTkRLlJU7YfYG4Y",
        maxPackages: 2,
        maxLength: 1,
        maxWidth: 1,
        maxHeight: 1,
        pickupDate: 1680134400000,
        dropoffDate: 1680134400000,
        daysToDeliver: 1,
        pickupLocationCoords: [28.7040592, 77.10249019999999],
        dropoffLocationCoords: [22.6708317, 71.5723953],
        allowedCategory: ["Documents", "Fragile"],
        radius: 0,
        price: 100,
        driverRouteId: 25,
      },
      aksPrice: 100.0,
      created_at: [2023, 3, 30, 1, 22, 26],
      updated_at: [2023, 3, 30, 1, 22, 26],
      status: "requested",
      package_request_id: 606,
    },
  ];
  orders = [
    [
      {
        id: 618,
        _package: {
          id: 616,
          sender: {
            first_name: "Nand",
            last_name: "Kadivar",
            phone: null,
            email: "kadivarnand007@gmail.com",
            password:
              "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
            gov_id_url: null,
            profile_pic_url: null,
            dob: null,
            address: null,
            city: null,
            latitude: "44.6476° N",
            longitude: "63.5728° W",
            province: null,
            postal_code: null,
            country: null,
            is_activated: null,
            is_verified: true,
            created_at: [2023, 3, 4, 0, 5, 1],
            updated_at: [2023, 3, 22, 23, 48, 43],
            username: null,
            authorities: null,
            user_id: 40,
            accountNonExpired: true,
            accountNonLocked: true,
            credentialsNonExpired: true,
            enabled: true,
          },
          title: "Package request by Nand Kadivar",
          description: "test 244",
          width: 1.0,
          length: 1.0,
          heigth: 0.0,
          pickup_address: "Cape Town",
          drop_address: "Cairo",
          created_at: [2023, 3, 30, 2, 44, 31],
          updated_at: [2023, 3, 30, 2, 44, 31],
        },
        sender: {
          first_name: "Nand",
          last_name: "Kadivar",
          phone: null,
          email: "kadivarnand007@gmail.com",
          password:
            "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: "44.6476° N",
          longitude: "63.5728° W",
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 4, 0, 5, 1],
          updated_at: [2023, 3, 22, 23, 48, 43],
          username: null,
          authorities: null,
          user_id: 40,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          enabled: true,
        },
        deliverer: {
          first_name: "shahraj",
          last_name: "singh",
          phone: null,
          email: "singhshahraj@gmail.com",
          password:
            "$2a$10$4oDo0UE4Ji.7dLMEIQD2KuUdNkrsmXmtoLEidWLCR25oYiZIR9SFC",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: null,
          longitude: null,
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 21, 20, 3, 19],
          updated_at: [2023, 3, 21, 20, 3, 50],
          username: null,
          authorities: null,
          user_id: 372,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          enabled: true,
        },
        driverRoute: {
          driverId: "372",
          driverName: "shahraj singh",
          sourceCity: "Cape Town",
          sourceCityReferenceId: "ChIJ1-4miA9QzB0Rh6ooKPzhf2g",
          destinationCity: "Cairo",
          destinationCityReferenceId: "ChIJ674hC6Y_WBQRujtC6Jay33k",
          maxPackages: 10,
          maxLength: 100,
          maxWidth: 100,
          maxHeight: 100,
          pickupDate: 1680220800000,
          dropoffDate: 1680307200000,
          daysToDeliver: 1,
          pickupLocationCoords: [-33.9248685, 18.4240553],
          dropoffLocationCoords: [30.0444196, 31.2357116],
          allowedCategory: ["Documents"],
          radius: 0,
          price: 1000,
          driverRouteId: 26,
        },
        pickup_code: 6971,
        drop_code: 6834,
        paymentStatus: 0,
        created_at: [2023, 3, 30, 2, 53, 25],
        updated_at: [2023, 3, 30, 2, 53, 25],
        canceled: false,
        started: false,
        delivered: false,
      },
      {
        id: 618,
        _package: {
          id: 616,
          sender: {
            first_name: "Nand",
            last_name: "Kadivar",
            phone: null,
            email: "kadivarnand007@gmail.com",
            password:
              "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
            gov_id_url: null,
            profile_pic_url: null,
            dob: null,
            address: null,
            city: null,
            latitude: "44.6476° N",
            longitude: "63.5728° W",
            province: null,
            postal_code: null,
            country: null,
            is_activated: null,
            is_verified: true,
            created_at: [2023, 3, 4, 0, 5, 1],
            updated_at: [2023, 3, 22, 23, 48, 43],
            username: null,
            authorities: null,
            user_id: 40,
            accountNonExpired: true,
            accountNonLocked: true,
            credentialsNonExpired: true,
            enabled: true,
          },
          title: "Package request by Nand Kadivar",
          description: "test 244",
          width: 1.0,
          length: 1.0,
          heigth: 0.0,
          pickup_address: "Cape Town",
          drop_address: "Cairo",
          created_at: [2023, 3, 30, 2, 44, 31],
          updated_at: [2023, 3, 30, 2, 44, 31],
        },
        sender: {
          first_name: "Nand",
          last_name: "Kadivar",
          phone: null,
          email: "kadivarnand007@gmail.com",
          password:
            "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: "44.6476° N",
          longitude: "63.5728° W",
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 4, 0, 5, 1],
          updated_at: [2023, 3, 22, 23, 48, 43],
          username: null,
          authorities: null,
          user_id: 40,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          enabled: true,
        },
        deliverer: {
          first_name: "shahraj",
          last_name: "singh",
          phone: null,
          email: "singhshahraj@gmail.com",
          password:
            "$2a$10$4oDo0UE4Ji.7dLMEIQD2KuUdNkrsmXmtoLEidWLCR25oYiZIR9SFC",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: null,
          longitude: null,
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 21, 20, 3, 19],
          updated_at: [2023, 3, 21, 20, 3, 50],
          username: null,
          authorities: null,
          user_id: 372,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          enabled: true,
        },
        driverRoute: {
          driverId: "372",
          driverName: "shahraj singh",
          sourceCity: "Cape Town",
          sourceCityReferenceId: "ChIJ1-4miA9QzB0Rh6ooKPzhf2g",
          destinationCity: "Cairo",
          destinationCityReferenceId: "ChIJ674hC6Y_WBQRujtC6Jay33k",
          maxPackages: 10,
          maxLength: 100,
          maxWidth: 100,
          maxHeight: 100,
          pickupDate: 1680220800000,
          dropoffDate: 1680307200000,
          daysToDeliver: 1,
          pickupLocationCoords: [-33.9248685, 18.4240553],
          dropoffLocationCoords: [30.0444196, 31.2357116],
          allowedCategory: ["Documents"],
          radius: 0,
          price: 1000,
          driverRouteId: 26,
        },
        pickup_code: 6971,
        drop_code: 6834,
        paymentStatus: 0,
        created_at: [2023, 3, 30, 2, 53, 25],
        updated_at: [2023, 3, 30, 2, 53, 25],
        canceled: false,
        started: true,
        delivered: false,
      },
      {
        id: 618,
        _package: {
          id: 616,
          sender: {
            first_name: "Nand",
            last_name: "Kadivar",
            phone: null,
            email: "kadivarnand007@gmail.com",
            password:
              "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
            gov_id_url: null,
            profile_pic_url: null,
            dob: null,
            address: null,
            city: null,
            latitude: "44.6476° N",
            longitude: "63.5728° W",
            province: null,
            postal_code: null,
            country: null,
            is_activated: null,
            is_verified: true,
            created_at: [2023, 3, 4, 0, 5, 1],
            updated_at: [2023, 3, 22, 23, 48, 43],
            username: null,
            authorities: null,
            user_id: 40,
            accountNonExpired: true,
            accountNonLocked: true,
            credentialsNonExpired: true,
            enabled: true,
          },
          title: "Package request by Nand Kadivar",
          description: "test 244",
          width: 1.0,
          length: 1.0,
          heigth: 0.0,
          pickup_address: "Cape Town",
          drop_address: "Cairo",
          created_at: [2023, 3, 30, 2, 44, 31],
          updated_at: [2023, 3, 30, 2, 44, 31],
        },
        sender: {
          first_name: "Nand",
          last_name: "Kadivar",
          phone: null,
          email: "kadivarnand007@gmail.com",
          password:
            "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: "44.6476° N",
          longitude: "63.5728° W",
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 4, 0, 5, 1],
          updated_at: [2023, 3, 22, 23, 48, 43],
          username: null,
          authorities: null,
          user_id: 40,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          enabled: true,
        },
        deliverer: {
          first_name: "shahraj",
          last_name: "singh",
          phone: null,
          email: "singhshahraj@gmail.com",
          password:
            "$2a$10$4oDo0UE4Ji.7dLMEIQD2KuUdNkrsmXmtoLEidWLCR25oYiZIR9SFC",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: null,
          longitude: null,
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 21, 20, 3, 19],
          updated_at: [2023, 3, 21, 20, 3, 50],
          username: null,
          authorities: null,
          user_id: 372,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          enabled: true,
        },
        driverRoute: {
          driverId: "372",
          driverName: "shahraj singh",
          sourceCity: "Cape Town",
          sourceCityReferenceId: "ChIJ1-4miA9QzB0Rh6ooKPzhf2g",
          destinationCity: "Cairo",
          destinationCityReferenceId: "ChIJ674hC6Y_WBQRujtC6Jay33k",
          maxPackages: 10,
          maxLength: 100,
          maxWidth: 100,
          maxHeight: 100,
          pickupDate: 1680220800000,
          dropoffDate: 1680307200000,
          daysToDeliver: 1,
          pickupLocationCoords: [-33.9248685, 18.4240553],
          dropoffLocationCoords: [30.0444196, 31.2357116],
          allowedCategory: ["Documents"],
          radius: 0,
          price: 1000,
          driverRouteId: 26,
        },
        pickup_code: 6971,
        drop_code: 6834,
        paymentStatus: 0,
        created_at: [2023, 3, 30, 2, 53, 25],
        updated_at: [2023, 3, 30, 2, 53, 25],
        canceled: true,
        started: false,
        delivered: false,
      },
      {
        id: 618,
        _package: {
          id: 616,
          sender: {
            first_name: "Nand",
            last_name: "Kadivar",
            phone: null,
            email: "kadivarnand007@gmail.com",
            password:
              "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
            gov_id_url: null,
            profile_pic_url: null,
            dob: null,
            address: null,
            city: null,
            latitude: "44.6476° N",
            longitude: "63.5728° W",
            province: null,
            postal_code: null,
            country: null,
            is_activated: null,
            is_verified: true,
            created_at: [2023, 3, 4, 0, 5, 1],
            updated_at: [2023, 3, 22, 23, 48, 43],
            username: null,
            authorities: null,
            user_id: 40,
            accountNonExpired: true,
            accountNonLocked: true,
            credentialsNonExpired: true,
            enabled: true,
          },
          title: "Package request by Nand Kadivar",
          description: "test 244",
          width: 1.0,
          length: 1.0,
          heigth: 0.0,
          pickup_address: "Cape Town",
          drop_address: "Cairo",
          created_at: [2023, 3, 30, 2, 44, 31],
          updated_at: [2023, 3, 30, 2, 44, 31],
        },
        sender: {
          first_name: "Nand",
          last_name: "Kadivar",
          phone: null,
          email: "kadivarnand007@gmail.com",
          password:
            "$2a$10$4RHkFFBe0Fm9wyDK9m.yWer28Ycko.Y8Yi.ziPXsHwiP/.WbTWgLG",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: "44.6476° N",
          longitude: "63.5728° W",
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 4, 0, 5, 1],
          updated_at: [2023, 3, 22, 23, 48, 43],
          username: null,
          authorities: null,
          user_id: 40,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          enabled: true,
        },
        deliverer: {
          first_name: "shahraj",
          last_name: "singh",
          phone: null,
          email: "singhshahraj@gmail.com",
          password:
            "$2a$10$4oDo0UE4Ji.7dLMEIQD2KuUdNkrsmXmtoLEidWLCR25oYiZIR9SFC",
          gov_id_url: null,
          profile_pic_url: null,
          dob: null,
          address: null,
          city: null,
          latitude: null,
          longitude: null,
          province: null,
          postal_code: null,
          country: null,
          is_activated: null,
          is_verified: true,
          created_at: [2023, 3, 21, 20, 3, 19],
          updated_at: [2023, 3, 21, 20, 3, 50],
          username: null,
          authorities: null,
          user_id: 372,
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
          enabled: true,
        },
        driverRoute: {
          driverId: "372",
          driverName: "shahraj singh",
          sourceCity: "Cape Town",
          sourceCityReferenceId: "ChIJ1-4miA9QzB0Rh6ooKPzhf2g",
          destinationCity: "Cairo",
          destinationCityReferenceId: "ChIJ674hC6Y_WBQRujtC6Jay33k",
          maxPackages: 10,
          maxLength: 100,
          maxWidth: 100,
          maxHeight: 100,
          pickupDate: 1680220800000,
          dropoffDate: 1680307200000,
          daysToDeliver: 1,
          pickupLocationCoords: [-33.9248685, 18.4240553],
          dropoffLocationCoords: [30.0444196, 31.2357116],
          allowedCategory: ["Documents"],
          radius: 0,
          price: 1000,
          driverRouteId: 26,
        },
        pickup_code: 6971,
        drop_code: 6834,
        paymentStatus: 0,
        created_at: [2023, 3, 30, 2, 53, 25],
        updated_at: [2023, 3, 30, 2, 53, 25],
        canceled: false,
        started: false,
        delivered: true,
      },
    ],
  ];
  listings = [
    {
      driverId: "40",
      driverName: "Nand undefined",
      sourceCity: "Halifax",
      sourceCityReferenceId: "ChIJwfrbBxQhWksR3C2LQ6bja2Y",
      destinationCity: "Sydney",
      destinationCityReferenceId: "ChIJFTRyfjb7Z0sRh4Awe5tTg6c",
      maxPackages: 1,
      maxLength: 1,
      maxWidth: 1,
      maxHeight: 1,
      pickupDate: 1680480000000,
      dropoffDate: 1680652800000,
      daysToDeliver: 1,
      pickupLocationCoords: [44.6475811, -63.5727683],
      dropoffLocationCoords: [46.1367899, -60.19422399999999],
      allowedCategory: ["Fragile", "Documents"],
      radius: 0,
      price: 100,
      driverRouteId: 31,
    },
  ];

  imageUrl = "data:image/png;base64,dW5kZWZpbmVk";
}

export default Data;
